portal/base/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("login/", views.loginPage, name="login"),
    path("logout/", views.logoutUser, name="logout"),
    path("register/", views.registerPage, name="register"),
    # path("", views.dashbord, name="home"),
    path("", views.home, name="home"),
    path("profile/<str:pk>", views.userProfile, name="user-profile"),
    path("vendors/", views.provider_activity.as_view(), name="list-vendors"),
    path(
        "edit-customer/<int:id>", views.EditCustomerView, name="edit-customer"
    ),
    path(
        "edit-customer-config/<int:id>",
        views.EditCustomerConfigView,
        name="edit-customer-config",
    ),
    path(
        "vendor-profile/<int:id>", views.vendorProfile, name="vendor-profile"
    ),
    path("plan/", views.planView, name="plan"),
    path("extend-plan/<int:id>", views.extendPlan_aj, name="extend-plan"),
    path(
        "ajax/extend-plan/",
        views.ValidateExtendPlan.as_view(),
        name="extend-plan-ajax",
    ),
    # path('invoice-form/<int:planPrice_id>/<int:total_price>', views.invoiceForm, name="invoice-form"),
    # path(r'^invoice-form/(?P<pr>\d+)(?:/(?P<tpr>\d+))?', views.invoiceDetailView, name="invoice-form"),
    # path(r'^invoice-form/(?P<pr>\d+)(?:/(?P<tpr>\d+))?', views.invoiceDetailView, name="invoice-form"),
    path(
        "invoice-form/<str:pr>/<str:tpr>",
        views.invoiceRegisterView,
        name="invoice-form",
    ),
    path(
        "<int:pk>/edit",
        views.invoiceDetailView.as_view(),
        name="invoice-edit",
    ),
    # (r'^question/(?P<pk>\d+)(?:/(?P<npk>\d+))?
    path("invoice-list/", views.invoiceList, name="invoice-list"),
    path("dashbord/", views.dashbord, name="dashbord"),
    path("index/", views.index, name="index"),
    # path('ticket/', views.createTicket, name="ticket"),
    # path('ticket/', views.ticketList, name="ticket"),
    path("about/", views.aboutUs, name="about"),
    path("test", views.test, name="test"),
    # path('edit-account/<int:id>', views.editAccountExchange, name='edit-account'),
    path(
        "account/<int:pk>/edit",
        views.EditAccountExchange.as_view(),
        name="edit-account",
    ),
    path(
        "account/<int:pk>/delete",
        views.DeleteAccountExchange.as_view(),
        name="delete-account",
    ),
    path(
        "create-account", views.createAccountExchange, name="create-account"
    ),
]

portal/portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("base.urls")),
    path("tickets/", include("tickets.urls")),
    path("signals/", include("signals.urls")),
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("img/favicon.ico")),
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portal/signals/urls.py
from django.urls import path
from . import views

app_name = "signals"
urlpatterns = [
    path(
        "create-signal/",
        views.SignalCreateView.as_view(),
        name="create-signal",
    ),
    path(
        "detail/<int:pk>",
        views.SignalDetailView.as_view(),
        name="signal-detail",
    ),
    path("", views.SignalListView.as_view(), name="list-signal"),
    path("spot", views.SignalSpotListView.as_view(), name="list-signal-spot"),
    path(
        "future",
        views.SignalFutureListView.as_view(),
        name="list-signal-future",
    ),
    path(
        "ajax/create-signal/",
        views.GetExchangePriceView.as_view(),
        name="create-signal-ajax",
    ),
]

portal/signals/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from base.models import Customer, Provider, Exchange


class Signal(models.Model):
    status = models.IntegerField(default=0, null=True, blank=True)

    # typ = models.IntegerField(default=0, choices=((1, 'Spot'), (2, 'Future')))
    typ = models.IntegerField(default=0)
    side = models.IntegerField(default=0)
    number_ep = models.IntegerField(default=0, null=True, blank=True)
    ep1 = models.FloatField(default=0, null=True, blank=True)
    ep2 = models.FloatField(default=0, null=True, blank=True)
    ep3 = models.FloatField(default=0, null=True, blank=True)
    ep4 = models.FloatField(default=0, null=True, blank=True)
    number_tp = models.IntegerField(default=0, null=True, blank=True)
    sl_number = models.FloatField(default=0, null=True, blank=True)
    # be = models.CharField(max_length=40, null=True,blank=True)
    Llv = models.FloatField(default=0, null=True, blank=True)
    lv_typ = models.FloatField(default=0, null=True, blank=True)
    en_user = models.IntegerField(default=0, null=True, blank=True)
    job_name = models.CharField(max_length=20, null=True, blank=True)
    updated = models.DateTimeField(null=True, blank=True)
    created = models.DateTimeField(null=True, blank=True)
    provider = models.ForeignKey(
        Provider, on_delete=models.SET_NULL, null=True, blank=True
    )
    exchange = models.ForeignKey(
        Exchange, on_delete=models.SET_NULL, null=True
    )

    class Meta:
        db_table = "signal"

    def __str__(self):
        return self.typ


class SignalDt(models.Model):
    signal = models.ForeignKey(Signal, on_delete=models.SET_NULL, null=True)
    tp = models.FloatField(default=0)
    tp_percent = models.PositiveIntegerField(default=0)
    updated = models.DateTimeField(null=True, blank=True)
    created = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = "signal_dt"

    def __str__(self):
        return f"Id: {self.pk }, {self.signal} for SignalId: {self.signal.pk}"


class SignalOrder(models.Model):
    client_id = models.CharField(max_length=200, null=False)
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, null=True
    )
    exchange = models.ForeignKey(
        Exchange, on_delete=models.SET_NULL, null=True
    )
    api_key = models.CharField(max_length=100, null=False)
    api_secret = models.CharField(max_length=100, null=False)
    api_passphrase = models.CharField(max_length=100, null=False)
    sig_typ = models.CharField(max_length=100, null=True)
    side = models.IntegerField(default=0, null=True)
    symb = models.CharField(max_length=20, null=True)
    amount_db = models.FloatField(default=0)
    pr_sym_db = models.FloatField(default=0)
    pr_sym_set = models.FloatField(default=0)
    ep = models.FloatField(default=0)
    ep_opt = models.FloatField(default=0)
    sl = models.FloatField(default=0, null=False, blank=True)
    trail_en = models.IntegerField(default=0, null=True, blank=True)
    trail_tp = models.IntegerField(default=0, null=True, blank=True)
    trail_sl = models.IntegerField(default=0, null=True, blank=True)
    status = models.IntegerField(default=0)
    number = models.IntegerField(default=1)
    job = models.CharField(max_length=200, null=False)
    bin_order_id = models.CharField(max_length=20, null=False)
    signal = models.ForeignKey(Signal, on_delete=models.SET_NULL, null=True)
    amount_set = models.IntegerField(default=0, null=False, blank=True)
    ep_pre = models.IntegerField(default=0, null=True, blank=True)
    updated = models.DateTimeField(null=True, blank=True)
    created = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = "signal_order"


class SisgnalOrderDt(models.Model):
    order = models.ForeignKey(
        SignalOrder, on_delete=models.SET_NULL, null=True
    )
    client_id = models.CharField(max_length=100, null=False)
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, null=True
    )
    symb = models.CharField(max_length=20, null=False)
    tp = models.FloatField(default=0)
    tp_am = models.FloatField(default=0)
    status = models.IntegerField(default=1)
    bin_order_id = models.CharField(max_length=20, null=False)
    signal = models.ForeignKey(Signal, on_delete=models.SET_NULL, null=True)
    updated = models.DateTimeField(null=True)
    created = models.DateTimeField(null=True)

    class Meta:
        db_table = "signal_order_dt"


class SigOrderSl(models.Model):
    order_id = models.IntegerField
    client_id = models.CharField(max_length=100, null=False)
    user_id = models.IntegerField(default=0)
    symb = models.CharField(max_length=20, null=False)
    sl = models.FloatField(default=0)
    status = models.IntegerField(default=0)
    number = models.IntegerField(default=1)
    bin_order_id = models.CharField(max_length=20, null=False)
    signal = models.ForeignKey(
        SignalOrder, on_delete=models.SET_NULL, null=True
    )
    amount_set = models.FloatField(default=0)
    updated = models.DateTimeField(null=True)
    created = models.DateTimeField(null=True)

    class Meta:
        db_table = "signal_order_sl"


class MarketPrice(models.Model):
    name = models.CharField(max_length=30, null=False)
    prc = models.FloatField(default=0)
    pre_prc = models.FloatField(default=0)
    side = models.IntegerField(default=0)
    updated = models.DateTimeField(null=True)
    created = models.DateTimeField(null=True)

    class Meta:
        db_table = "market_price"

    def __str__(self):
        return self.name

portal/signals/views.py
from django.views.generic.edit import CreateView
from django.views.generic import ListView
from .models import Signal, MarketPrice, SignalDt
from .form import SignalForm, SignalDetailInlineFormset
from django.views.generic.edit import View
from django.shortcuts import get_object_or_404, redirect
from django.db import connections
from datetime import datetime
from django.http import JsonResponse

class SignalDetailView(ListView):
    model = SignalDt
    paginate_by = 15

    context_object_name = "signal_detail"
    template_name = "signal_detail.html"

    def get_context_data(self, **kwargs):
        context = super(SignalDetailView, self).get_context_data(**kwargs)
        s_detail = (
            SignalDt.objects.filter(signal=self.kwargs["pk"])
                .values()
                .order_by("tp")
        )

        context = {"signal_detail": s_detail}
        return context


class SignalListView(ListView):
    model = Signal
    paginate_by = 15
    ordering = "-id"
    context_object_name = "signals"
    template_name = "signal_list.html"

    def get_queryset(self):
        try:
            with connections["default"].cursor() as cursor:
                print(self.request.user.id)
                cursor.execute(
                    f"select id, id_id, typ,side, lv, ep1, ep2,ep3,ep4, sl_number ,ex_name, updated, created, provider_name,avatar,status  from v_signal where id_id={self.request.user.id}"
                )
                return dictfetchall(cursor)

        except:
            print("None")
            context = {"signals": "None"}
            return context


class SignalSpotListView(ListView):
    model = Signal
    paginate_by = 15
    ordering = "-id"
    context_object_name = "signals"
    template_name = "signal_list_spot.html"

    def get_queryset(self):
        try:
            with connections["default"].cursor() as cursor:
                print(self.request.user.id)
                cursor.execute(
                    f"select id, id_id, typ,side,lv, ep1, ep2,ep3,ep4, sl_number ,ex_name, updated, created, provider_name,avatar,status  from v_signal where id_id={self.request.user.id}"
                )
                return dictfetchall(cursor)

        except:
            print("None")
            context = {"signals": "None"}
            return context


class SignalFutureListView(ListView):
    model = Signal
    paginate_by = 15
    ordering = "-id"
    context_object_name = "signals"
    template_name = "signal_list_future.html"

    def get_queryset(self):
        try:
            with connections["default"].cursor() as cursor:
                cursor.execute(
                    f"select id, id_id, typ,side,lv, ep1, ep2,ep3,ep4, sl_number ,ex_name, updated, created, provider_name,avatar,status  from v_signal where id_id={self.request.user.id}"
                )
                return dictfetchall(cursor)

        except:
            print("None")
            context = {"signals": "None"}
            return context


def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [dict(zip(columns, row)) for row in cursor.fetchall()]


class SignalCreateView(CreateView):
    form_class = SignalForm
    template_name = "signal_form.html"

    def get_context_data(self, **kwargs):

        context = super(SignalCreateView, self).get_context_data(**kwargs)
        # context["provider"]= models.Provider.objects.get(id=1)
        if self.request.POST:
            context["signal_detail_formset"] = SignalDetailInlineFormset(
                self.request.POST
            )
        else:
            context["signal_detail_formset"] = SignalDetailInlineFormset()
        return context

    def post(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)

        signal_detail_formset = SignalDetailInlineFormset(self.request.POST)

        if form.is_valid() and signal_detail_formset.is_valid():
            return self.form_valid(form, signal_detail_formset)
        else:
            print(form.errors)
            print(signal_detail_formset.errors)
            return self.form_invalid(form, signal_detail_formset)
 # to do change provider_id
    def form_valid(self, form, signal_detail_formset):
        self.object = form.save(commit=False)
        form.instance.provider_id = 1
        form.instance.updated = datetime.now()
        form.instance.created = datetime.now()
        self.object.save()
        # saving ProductMeta Instances
        signal_metas = signal_detail_formset.save(commit=False)
        # print(signal_metas.count())
        for meta in signal_metas:
            meta.signal = self.object
            meta.updated = datetime.now()
            meta.created = datetime.now()
            meta.save()
        # return redirect(reverse("product:product_list"))
        print ('back to signals ...')
        return redirect("/signals")

    def form_invalid(self, form, signal_detail_formset):
        return self.render_to_response(
            self.get_context_data(
                form=form, signal_detail_formset=signal_detail_formset
            )
        )

class GetExchangePriceView(View):
    def get(self, request):
        p_exchange = request.GET.get("p_exchange", None)
        exchangePrice = MarketPrice.objects.get(name=p_exchange)
        data = {
            "p_exchange": exchangePrice.prc,
        }
        print('data is ', data)
        return JsonResponse(data)

portal/signals/templates/signal_form.html
{% extends 'main.html' %}
{% block content %}

<form id="id_form" action="" method="post">
    {% csrf_token %}
    {{ form.non_form_errors }}
    {{ form.management_form }}

    {% include "partials/model_inline.html" with title='Register Signal' text_body='Are you sure to register a siganl' %}
    {% include "partials/alert_inline.html" %}
    <div class="row">
        <div class="col-lg-12">
            <div class="card card-default">
                <div class="card-header card-header-border-bottom">
                    <h2>Create Signal</h2>
                </div>
                <div class="card-body">
                    <div class="col-12">
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-6 ">
                                            <label for="id_status">status</label>
                                            <select id="id_status" class="form-control" name="status"
                                                    value="{{ form.status}}">
                                                <option value="1"> Active</option>
                                                <option value="2"> Inactive</option>
                                            </select>
                                        </div>

                                        <div class="col-6 form-group">
                                            <label for="id_typ">Type</label>
                                            <select id="id_typ" class="form-control" name="typ" value="{{ form.typ}}">
                                                <option value="1">Spot</option>
                                                <option value="2">Future</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class=" col-6 id_lev">
                                <div class="row">
                                    <div class="col-6 form-group">
                                        <label for="id_llv">LLV</label>
                                        <input id="id_llv" type="number" step="any" min="0" class="form-control"
                                               name="llv">
                                    </div>
                                    <div class="col-6 form-group">
                                        <label for="id_lv_typ">lv_typ</label>
                                        <input id="id_lv_typ" class="form-control" name="typ" value={{form.lv_typ.value}}>
                                    </div>
                                </div>
                            </div>
                        </div>


                        <div class="row">
                            <div class="col-3">
                                <div class="form-group">
                                    <label for="id_side">Buy/Sell</label>
                                    <select id="id_side" class="form-control" name="side" value="{{form.side}}">
                                        <option value="1">Buy</option>
                                        <option value="2">Sell</option>
                                    </select>
                                </div>
                            </div>

                            <div class="col-3">
                                <div class="form-group">
                                    <label for="id_exchange">Exchange</label>
                                    <select id="id_exchange" class="form-control" name="exchange"
                                            value={{form.exchange}}

                                    </select>
                                </div>
                            </div>

                            <div class="col-6">
                                <div class="form-group">
                                    <label for="id_sl_number">Stop Loss</label>
                                    <input id="id_sl_number" type="number" step=any min="0" class="form-control"
                                           name="sl_number">
                                </div>
                            </div>
                        </div>


                        <div class="row">
                            <div class="col-3">
                                <div class="form-group">
                                    <label for="id_ep1">Ep #1</label>
                                    <input id="id_ep1" type="number" step=any min="0" class="form-control"
                                           name="ep1" value={{form.ep1.value}}>
                                </div>
                            </div>

                            <div class="col-3">
                                <div class="form-group">
                                    <label for="id_ep2">Ep #2</label>
                                    <input id="id_ep2" type="number" step=any class="form-control" name="ep2"
                                           min="0">
                                </div>
                            </div>
                            <div class="col-3">
                                <div class="form-group">
                                    <label for="id_ep3">Ep #3</label>
                                    <input id="id_ep3" type="number" step=any min="0" class="form-control"
                                           name="ep3">
                                </div>
                            </div>

                            <div class="col-3">
                                <div class="form-group">
                                    <label for="id_ep4">Ep #4</label>
                                    <input id="id_ep4" type="number" step=any min="0" class="form-control"
                                           name="ep4">
                                </div>
                            </div>

                        </div>

                        <div class="form-footer pt-5 border-top">
                                <div class="row d-flex align-items-center">
                                    <div class="col-3 ">
                                        <div class="form-group">
                                            <label for="id_number_tp">number_tp</label>
                                            <select id="id_number_tp" name="number_tp" class="form-control">
                                                <option value="1">1</option>
                                                <option value="2">2</option>
                                                <option value="3">3</option>
                                                <option value="4">4</option>
                                                <option value="5">5</option>
                                                <option value="6">6</option>
                                                <option value="7">7</option>
                                                <option value="8">8</option>
                                                <option value="9">9</option>
                                                <option value="10">10</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-6 mx-5" id="alert_percent">
                                        <h3>TP Percent <span id="id_sum_percent" class="badge badge-warning">0%</span></h3>
                                    </div>
                                </div>
                            </div>
                            {{ signal_detail_formset.non_form_errors }}
                            {{ signal_detail_formset.management_form }}
                            <ul>
                                {% for f in signal_detail_formset %}
                                <li class="li_c">
                                    <div class="d-flex py-1 inline {{ signal_detail_formset.prefix }}">
                                        <div type="number" step="any" min="0">{{f.tp.label}} : {{ f.tp }}</div>
                                        <div class="ml-5" type="number" step="1" min="0">{{f.tp_percent.label}}:
                                            {{f.tp_percent }}
                                        </div>
                                        {% if signal_detail_formset.can_delete %}
                                        <div class="ml-5">{{ f.DELETE }} {{ f.DELETE.label }}</div>
                                        {% endif %}
                                    </div>
                                </li>
                                {% endfor %}

                            </ul>
                        </div>
                        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                            <button id="id_submit" type="button" class="btn btn-primary" data-toggle="modal" data-target="#save_model">Submit Signal
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</form>

<script>
   $("#id_save").click(function(){
        if  ($("#id_sum_percent").html() != '100%'){
            alert ('Sum of Tps should be 100%');
            return false;
       }else{
            document.getElementById("id_form").submit();
            return true;
            }
   });
    $(document).ready(function(){
        $('#id_typ').change(function(){
            //alert( $("#id_typ").find(":selected").val());
            if ( $("#id_typ").val() == 1 ){
                $(".id_lev").hide();
            }else{
                $(".id_lev").show();
            }
        }) // end id_typ change

       $("#id_number_tp").change(function(){
        // alert( $("#id_number_tp").find(":selected").val());
            $(".li_c").hide();
            for (let i = 1; i <= $("#id_number_tp").find(":selected").val(); ++i) {
                $(".li_c:nth-child("+i+")").fadeIn();

            }
        }) // end number tp change
        $(".li_c").hide();
        $(".id_lev").hide();
        $(".li_c").first().fadeIn();

        $(".ml-5").change(function(){
            var p_sum_percent=0;
            var i=0;
             $(".ml-5").each(function(){
             //alert($("#id_signaldt_set-"+i+"-tp_percent").val());
                p_sum_percent +=  parseInt($("#id_signaldt_set-"+i+"-tp_percent").val());
                i++;
                })
                 if (p_sum_percent < 100) {
                    $("#id_sum_percent").attr('class','badge badge-warning');
                    $("#id_sum_percent").html(p_sum_percent+'%');
                 }else if (p_sum_percent == 100){
                    $("#id_sum_percent").attr('class','badge badge-success');
                    $("#id_sum_percent").html(p_sum_percent+'%');
                 }else if (p_sum_percent > 100){
                    $("#id_sum_percent").attr('class','badge badge-danger');
                    $("#id_sum_percent").html(p_sum_percent+'%');
                 }
        })
////////////////////////////////////////
       $("#id_exchange").change(function(){
       //alert( $("#id_exchange").find(":selected").html());
       //alert( $("#id_ep3").val());
        var p_exchange = $("#id_exchange").find(":selected").html();
        //alert( p_exchange);
        $.ajax({
            url: '/signals/ajax/create-signal/',
            data: {
                'p_exchange': p_exchange,
                  },
            dataType: 'json',
            success: function (data) {
             //  $("#id_ep1").html(data.p_exchange);
               $("#id_ep1").val(data.p_exchange);
            }
        }); //ajax
    })
////////////////////////////////////////
     })


</script>
{% endblock %}

portal/signals/templates/signal_list.html
{% extends 'main.html' %}
{% block content %}
<div class="row">
    <div class="col-lg-12">
        <div class="card card-default">
            <div class="card-header card-header-border-bottom">
                <h2>All Signals (spot and future)</h2>
            </div>


            <table class="table">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">No#</th>
                    <th scope="col">type</th>
                    <th scope="col">side</th>
                    <th scope="col">ep1</th>
                    <th scope="col">ep2</th>
                    <th scope="col">ep3</th>
                    <th scope="col">ep4</th>
                    <th scope="col">sl</th>
                    <th scope="col">exchange</th>
                    <th scope="col">status</th>
                    <th scope="col">created</th>
                    <th scope="col">updated</th>
                    <th scope="col">signal provider</th>
                </tr>
                </thead>

                <tbody>
                {% for s in signals %}
                    <tr>
                        <td><a href="{% url 'signals:signal-detail' s.ID %}">{{s.ID}}# </a></td>
                        <td>{{s.TYP}}</td>
                        <td>{{s.SIDE}}</td>
                        <td>{{s.EP1}}</td>
                        <td>{{s.EP2}}</td>
                        <td>{{s.EP3}}</td>
                        <td>{{s.EP4}}</td>
                        <td>{{s.SL_NUMBER}}</td>
                        <td>{{s.EX_NAME}}</td>
                        <td>{{s.STATUS}}</td>
                        <td>{{ s.CREATED }}</td>
                        <td>{{ s.UPDATED }}</td>
                        <td><img src="{{s.AVATAR}}" width="30" height="30">{{s.PROVIDER_NAME}}</td>
                    </tr>

                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
    <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
    </div>
</div>
{% endblock%}