portal/base/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("login/", views.loginPage, name="login"),
    path("logout/", views.logoutUser, name="logout"),
    path("register/", views.registerPage, name="register"),
    # path("", views.dashbord, name="home"),
    path("", views.home, name="home"),
    path("profile/<str:pk>", views.userProfile, name="user-profile"),
    path("vendors/", views.provider_activity.as_view(), name="list-vendors"),
    path(
        "edit-customer/<int:id>", views.EditCustomerView, name="edit-customer"
    ),
    path(
        "edit-customer-config/<int:id>",
        views.EditCustomerConfigView,
        name="edit-customer-config",
    ),
    path(
        "vendor-profile/<int:id>", views.vendorProfile, name="vendor-profile"
    ),
    path("plan/", views.planView, name="plan"),
    path("extend-plan/<int:id>", views.extendPlan_aj, name="extend-plan"),
    path(
        "ajax/extend-plan/",
        views.ValidateExtendPlan.as_view(),
        name="extend-plan-ajax",
    ),
    # path('invoice-form/<int:planPrice_id>/<int:total_price>', views.invoiceForm, name="invoice-form"),
    # path(r'^invoice-form/(?P<pr>\d+)(?:/(?P<tpr>\d+))?', views.invoiceDetailView, name="invoice-form"),
    # path(r'^invoice-form/(?P<pr>\d+)(?:/(?P<tpr>\d+))?', views.invoiceDetailView, name="invoice-form"),
    path(
        "invoice-form/<str:pr>/<str:tpr>",
        views.invoiceRegisterView,
        name="invoice-form",
    ),
    path(
        "<int:pk>/edit",
        views.invoiceDetailView.as_view(),
        name="invoice-edit",
    ),
    # (r'^question/(?P<pk>\d+)(?:/(?P<npk>\d+))?
    path("invoice-list/", views.invoiceList, name="invoice-list"),
    path("dashbord/", views.dashbord, name="dashbord"),
    path("index/", views.index, name="index"),
    # path('ticket/', views.createTicket, name="ticket"),
    # path('ticket/', views.ticketList, name="ticket"),
    path("about/", views.aboutUs, name="about"),
    path("test", views.test, name="test"),
    # path('edit-account/<int:id>', views.editAccountExchange, name='edit-account'),
    path(
        "account/<int:pk>/edit",
        views.EditAccountExchange.as_view(),
        name="edit-account",
    ),
    path(
        "account/<int:pk>/delete",
        views.DeleteAccountExchange.as_view(),
        name="delete-account",
    ),
    path(
        "create-account", views.createAccountExchange, name="create-account"
    ),
]

portal/portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("base.urls")),
    path("tickets/", include("tickets.urls")),
    path("signals/", include("signals.urls")),
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("img/favicon.ico")),
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portal/signals/urls.py
from django.urls import path
from . import views

app_name = "signals"
urlpatterns = [
    path(
        "create-signal/",
        views.SignalCreateView.as_view(),
        name="create-signal",
    ),
    path(
        "detail/<int:pk>",
        views.SignalDetailView.as_view(),
        name="signal-detail",
    ),
    path("", views.SignalListView.as_view(), name="list-signal"),
    path("spot", views.SignalSpotListView.as_view(), name="list-signal-spot"),
    path(
        "future",
        views.SignalFutureListView.as_view(),
        name="list-signal-future",
    ),
    path(
        "ajax/create-signal/",
        views.GetExchangePriceView.as_view(),
        name="create-signal-ajax",
    ),
]

portal/tickets/urls.py
from django.urls import path
from . import views

app_name = "tickets"
urlpatterns = [
    path("", views.TicketListView.as_view(), name="ticket-list"),
    path("create", views.TicketCreateView.as_view(), name="ticket-create"),
    path(
        "<int:pk>/add",
        views.TicketDetailExtendView.as_view(),
        name="ticket-add",
    ),
]

portal/base/models.py
from django.db import models
from django.contrib.auth.models import User


class PlanDuration(models.Model):
    name = models.CharField(max_length=50, null=False)
    duration = models.IntegerField(default=0)
    dsc = models.CharField(max_length=500, null=True, blank=True)
    status = models.IntegerField(default=0)

    class Meta:
        db_table = "plan_duration"

    def __str__(self):
        return self.name


class Plan(models.Model):
    name = models.CharField(max_length=50, null=False)
    dsc = models.CharField(max_length=500, null=True, blank=True)
    status = models.IntegerField(default=0)

    class Meta:
        db_table = "plan"

    def __str__(self):
        return self.name


class PlanPrice(models.Model):
    plan_name = models.CharField(max_length=50, null=False)
    plan_dure = models.CharField(max_length=50, null=False)
    plan = models.ForeignKey(Plan, on_delete=models.SET_NULL, null=True)
    planDuration = models.ForeignKey(
        PlanDuration, on_delete=models.SET_NULL, null=True
    )
    price = models.IntegerField(default=0)
    priceWithDisc = models.IntegerField(default=0)
    status = models.IntegerField(default=0)

    class Meta:
        db_table = "plan_price"

    def __str__(self):
        return self.plan_name + "---" + self.plan_dure


class Customer(models.Model):
    id = models.OneToOneField(
        User, on_delete=models.CASCADE, primary_key=True
    )
    first_name = models.CharField(max_length=150, null=True)
    last_name = models.CharField(max_length=150, null=True)
    phone = models.CharField(max_length=13, null=True, blank=True)
    email = models.EmailField(unique=True, null=True, blank=True)
    avatar = models.ImageField(
        null=True, upload_to="profile_image/", blank=True
    )
    password = models.CharField(max_length=150, null=True)
    status = models.IntegerField(default=0)
    plan = models.ForeignKey(
        Plan, on_delete=models.SET_NULL, null=True, blank=True
    )
    planDuration = models.ForeignKey(
        PlanDuration, on_delete=models.SET_NULL, null=True, blank=True
    )
    updated = models.DateTimeField(null=True, blank=True)
    created = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = "customer"

    def __str__(self):
        return self.first_name + " " + self.last_name


# Create your models here.
class Exchange(models.Model):
    name = models.CharField(max_length=50, null=False)
    typ = models.CharField(max_length=50, null=False)
    status = models.IntegerField(default=0)
    dsc = models.CharField(max_length=200, null=False)
    updated = models.DateTimeField(null=True, blank=True)
    created = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = "exchange"

    def __str__(self):
        return self.name


class ServiceType(models.Model):
    name = models.CharField(max_length=50, null=False)
    status = models.IntegerField(default=0)

    class Meta:
        db_table = "service_type"

    def __str__(self):
        return self.name


class Provider(models.Model):
    name = models.CharField(max_length=50, null=False)
    email = models.EmailField(unique=True, null=True)
    phone = models.CharField(max_length=13, null=True)
    dsc = models.CharField(max_length=200, null=True, blank=True)
    status = models.IntegerField(default=0)
    avatar = models.ImageField(
        null=True, upload_to="profile_image/", blank=True
    )
    channel = models.CharField(max_length=50, null=True)
    updated = models.DateTimeField(null=True, blank=True)
    created = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = "Provider"

    def __str__(self):
        return self.name


class ProviderPrice(models.Model):
    name = models.CharField(max_length=50, null=False)
    planDuration = models.ForeignKey(
        PlanDuration, on_delete=models.SET_NULL, null=True, blank=True
    )
    status = models.IntegerField(default=0)
    price = models.IntegerField(default=0)
    priceWithDisc = models.IntegerField(default=0)
    provider = models.ForeignKey(
        Provider, on_delete=models.SET_NULL, null=True, blank=True
    )

    class Meta:
        db_table = "Provider_price"

    def __str__(self):
        # return self.name + ' '+ str(self.priceWithDisct) + ' ' + str(self.price)
        return self.name


class CustomerConfig(models.Model):
    name = models.CharField(max_length=100, null=True)
    customer = models.ForeignKey(
        Customer, on_delete=models.CASCADE, null=True
    )
    active = models.IntegerField(default=1, null=True, blank=True)
    referal_key = models.CharField(max_length=100, null=True, blank=True)
    api_name = models.CharField(max_length=100, null=False)
    api_key = models.CharField(max_length=100, null=False)
    api_secret = models.CharField(max_length=100, null=False)
    api_passphrase = models.CharField(max_length=100, null=False)
    trading_pass = models.CharField(max_length=20, null=True, blank=True)
    provider = models.ForeignKey( Provider, on_delete=models.CASCADE, null=True, blank=True)
    channel_id = models.IntegerField(default=0, null=True, blank=True)
    ex_id = models.IntegerField(default=0, null=True, blank=True)
    amuont =  models.FloatField(default=0, null=True, blank=True)
    close_trade = models.IntegerField(default=0, null=True, blank=True)
    grace_percent = models.IntegerField(default=0, null=True, blank=True)
    trailing_en = models.IntegerField(default=0, null=True, blank=True)
    trailing_tp = models.IntegerField(default=0, null=True, blank=True)
    trailing_stop = models.CharField(max_length=50, null=True, blank=True)
    min_symb_interval = models.IntegerField(default=0, null=True, blank=True)
    blacklist_symb = models.CharField(max_length=100, null=True, blank=True)
    blacklist_pair = models.CharField(max_length=100, null=True, blank=True)
    use_ep_percent = models.IntegerField(default=1, null=True, blank=True)
    ep1_percent = models.IntegerField(default=0, null=True, blank=True)
    ep2_percent = models.IntegerField(default=0, null=True, blank=True)
    ep3_percent = models.IntegerField(default=0, null=True, blank=True)
    ep4_percent = models.IntegerField(default=0, null=True, blank=True)
    use_tp_percent = models.IntegerField(default=0, null=True, blank=True)
    tp1_percent = models.IntegerField(default=0, null=True, blank=True)
    tp2_percent = models.IntegerField(default=0, null=True, blank=True)
    tp3_percent = models.IntegerField(default=0, null=True, blank=True)
    tp4_percent = models.IntegerField(default=0, null=True, blank=True)
    tp5_percent = models.IntegerField(null=True, blank=True)
    tp6_percent = models.IntegerField(null=True, blank=True)
    tp7_percent = models.IntegerField(null=True, blank=True)
    tp8_percent = models.IntegerField(null=True, blank=True)
    tp9_percent = models.IntegerField(null=True, blank=True)
    tp10_percent = models.IntegerField(null=True, blank=True)
    status = models.IntegerField(default=0, null=True, blank=True)
    number_tp = models.PositiveIntegerField(default=0)
    updated = models.DateTimeField(null=True, blank=True)
    created = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = "customer_config"

    def __str__(self):
        return self.name


class Invoice(models.Model):
    trx_id = models.CharField(max_length=250, null=True)
    w_customer = models.CharField(max_length=50, null=True)
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, null=True
    )
    PlanPrice = models.ForeignKey(
        PlanPrice, on_delete=models.SET_NULL, null=True
    )
    total_price = models.IntegerField(default=0)
    status = models.IntegerField(default=0)
    updated = models.DateTimeField(null=True, blank=True)
    created = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = "invoice"


class Plan_feature(models.Model):
    name = models.CharField(max_length=50, null=False)
    status = models.IntegerField(default=0)
    dsc = models.CharField(max_length=200, null=True, blank=True)
    updated = models.DateTimeField(null=True, blank=True)
    created = models.DateTimeField(null=True, blank=True)
    plan = models.ForeignKey(Plan, on_delete=models.SET_NULL, null=True)

    class Meta:
        db_table = "plan_feature"

    def __str__(self):
        return self.name

portal/tickets/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from base.models import Customer


class TicketSubject(models.Model):  # 1 to many
    name = models.CharField(max_length=50, null=False)
    status = models.IntegerField(default=1, null=False, blank=True)
    dsc = models.CharField(max_length=300, null=True, blank=True)
    updated = models.DateTimeField(null=True, blank=True)
    created = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = "ticket_subject"

    def __str__(self):
        return self.name


class Ticket(models.Model):
    PRIORITY_CHOICES = (
        ("Low", "Low"),
        ("Medium", "Medium"),
        ("High", "High"),
        ("Critical", "Critical"),
    )
    STATUS_CHOICES = (
        ("Open", "Open"),
        ("Waiting On Submitter", "Waiting On Submitter"),
        ("In Progress", "In Progress"),
        ("Waiting On Support", "Waiting On Support"),
        ("Resolved", "Resolved"),
    )
    ticketSubject = models.ForeignKey(TicketSubject, on_delete=models.CASCADE)
    priority = models.CharField(
        max_length=10, choices=PRIORITY_CHOICES, blank=True
    )
    status = models.CharField(
        max_length=40, choices=STATUS_CHOICES, blank=True
    )
    user = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True)
    updated = models.DateTimeField(null=True, blank=True)
    created = models.DateTimeField(null=True, blank=True)

    def how_many_days_old(self):
        delta = timezone.now() - self.created
        return delta.days

    # def shortened_subject_str(self):
    #     return self.subject[0:20]

    # def get_absolute_url(self):
    #     return reverse('tickets:ticket_detail', args=[str(self.id)])

    def __str__(self):
        return self.ticketSubject.name + "-" + str(self.id)

    class Meta:
        db_table = "ticket"


class TicketDetail(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.SET_NULL, null=True)
    status = models.IntegerField(default=1)
    req = models.CharField(max_length=500, null=True, blank=True)
    resp = models.CharField(max_length=1000, null=True, blank=True)
    updated = models.DateTimeField(null=True, blank=True)
    created = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = "ticket_dt"

portal/tickets/forms.py
from django import forms
from .models import Ticket, TicketDetail, TicketSubject
from django.forms import ModelForm
from django.forms import inlineformset_factory


class TicketForm(ModelForm):
    class Meta:
        model = Ticket
        fields = ["priority", "ticketSubject"]


class TicketSubjectForm(ModelForm):
    class Meta:
        model = TicketSubject
        fields = "__all__"


# class TicketForm(forms.ModelForm):
#     class Meta:
#         model = Ticket
#
#         widgets = {
#             'description': forms.Textarea(),
#             'creator': forms.HiddenInput(),
#         }
#
#         fields = [
#             'ticketType',
#             'subject',
#             'project',
#             'description',
#             'priority',
#             'status',
#             'creator',
#             'owner',
#         ]
#
#         # help_texts = {
#         #     'subject': 'Group to which this message belongs to',
#         # }
#
#         # error_messages={
#         #     'required': 'Please enter your name'
#         # }


class TicketDetailForm(ModelForm):
    class Meta:
        model = TicketDetail
        fields = ["req"]

portal/templates/edit_customer.html
{% extends 'main.html' %}
{% block content %}
<div>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_form_errors }}
        {{ form.management_form }}
        <div hidden>{{form.id }}</div>
        {% if user.is_authenticated == True and request.user.id == form.id.value %}

        <div class="bg-white border rounded">
            <div class="row no-gutters">
                <div class="col-lg-4 col-xl-3">
                    <div class="profile-content-left profile-left-spacing pt-5 pb-3 px-3 px-xl-5">
                        <div class="card text-center widget-profile px-0 border-0">
                            <div class="card-img mx-auto rounded-circle">
                                <img src="{{form.avatar.value.url}}" width="50 100%">

                            </div>
                            <div class="card-body">
                                <h4 class="py-2 text-dark">{{request.user.username}}</h4>
                                <p id="id_status" hidden>{{form.status.value }}</p>
                                <p id="id_status_desc"><h4 class="py-2 text-dark"></h4></p>
                            </div>
                        </div>
                        <hr class="w-100">
                        <div class="contact-info pt-4">
                            <h5 class="text-dark mb-1">Contact Information</h5>
                            <p class="text-dark font-weight-medium pt-4 mb-2">Email address</p>
                            <p>{{form.email.value}}</p>
                            <p class="text-dark font-weight-medium pt-4 mb-2">Phone Number</p>
                            <p>{{form.phone.value}}</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-8 col-xl-9">
                    <div class="profile-content-right profile-right-spacing py-5">
                        <ul class="nav nav-tabs px-3 px-xl-5 nav-style-border" id="myTab" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" data-toggle="tab" href="#profile"
                                   aria-selected="true">Profile</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link " data-toggle="tab" href="#setting"
                                   aria-selected="false">Exchange Accounts</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" data-toggle="tab" href="#referal" aria-selected="false">Referal</a>
                            </li>
                        </ul>
                        <div class="tab-content px-3 px-xl-5" id="myTabContent">
                            <div class="tab-pane fade show active" id="profile">
                                <div class="tab-pane-content mt-5">
                                    <div class="form-group row mb-6">
                                        <label for="coverImage" class="col-sm-4 col-lg-2 col-form-label">User
                                            Image</label>
                                        <div class="col-sm-8 col-lg-10">
                                            <div class="custom-file mb-1">

                                                <input value={{form.avatar.value}} name="avatar" type="file"
                                                       accept="image/*" class="custom-file-input" id="id_avatar">
                                                <label class="custom-file-label" for="id_avatar">Choose file...</label>

                                                <div class="invalid-feedback">Example invalid custom file feedback</div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row mb-2">
                                        <div class="col-6">
                                            <label for="id_first_name">First name</label>
                                            <input name="first_name" class="form-control"
                                                   value={{form.first_name.value}}>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label for="id_last_name">Last name</label>
                                                <input id="id_last_name" name="last_name" class="form-control"
                                                       value={{form.last_name.value}}>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row mb-2">
                                        <div class="col-6 form-group">
                                            <div class="form-group mb-4">
                                                <label for="id_phone">Phone:</label>
                                                <input id="id_phone" name="phone" class="form-control"
                                                       value={{form.phone.value}}>
                                            </div>
                                        </div>
                                        <div class="col-6 form-group">
                                            <div class="form-group mb-4">
                                                <label for="id_email">Email:</label>
                                                <input id="id_email" name="email" class="form-control"
                                                       value={{form.email.value}}>
                                            </div>
                                        </div>
                                    </div>
                                    <p id="id_status" hidden>{{form.status}}</p>

                                    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                                        <button type="submit" value="update" class="btn btn-primary btn-pill">Update Profile
                                        </button>
                                    </div>

                                </div>
                            </div>
                            <div class="tab-pane fade" id="setting">
                                <p class="card-text mx-3">{% include "partials/customer_conf_inline.html" %}</p>
                            </div>

                            <div class="tab-pane fade" id="referal">
                                <div class="row mb-5">
                                    <div class="col sm-1">
                                        <div class="form-group mb-2">
                                            <div class="input-group input-group-sm mt-5">
                                                <div class="input-group-prepend"><span
                                                        class="input-group-text font-weight-medium">Referal</span>
                                                </div>
                                                <input class="form-control" type="text" readonly id="id_ref"
                                                       value="564654564ref">
                                            </div>
                                        </div>
                                        <div class="col 3">
                                            <button type="button" id="copy" class="btn btn-primary mb-2 btn-pill"><span
                                                    class="bi bi-clipboard"></span> Copy to clipboard
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif%}
    </form>
</div>
<script>
    $(document).ready(function(){
    $("#copy").click(function(){

        $("#id_ref").select();
        document.execCommand("copy");
    });
       // alert($("#id_status").html())
        if ( $("#id_status").html() == 1 ){
            $("#id_status_desc").html("Active");
        }else{
            $("#id_status_desc").html("Inactive");
        }
    })

















</script>
{% endblock%}

portal/templates/extend_plan1.html
{% extends 'main.html' %}
{% block content %}
<form method="post" id="id_page">
    {% csrf_token %}
    <div class="row">
        <div class="col-lg-12">
            <div class="card card-default">
                <div class="card-header card-header-border-bottom">
                    <h2>Subscribe to Vendor Services</h2>
                </div>
                <div class="card-body">
                    <div class="col-12">
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <label for="id_plan_duration">plan duration</label>

                                    <select id="id_plan_duration" class="form-control" name="plan_duration"
                                            value={{plan_duration.planDuration}}
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="id_provider_name">provider name</label>
                                    <select id="id_provider_name" class="form-control" name="provider_name"
                                            value={{provider_name.providerName}}
                                    </select>
                                </div>
                                <div class="form-group">

                                    <div class="row">
                                        <div class="col-6 my-3  align-self-center">
                                            <label class="sr-only" for="gift_id">Gift Code</label>
                                            <input id="gift_id" type="" class="form-control" name="gift_id" placeholder="Gift Code">
                                        </div>
                                        <div class="col-6  align-self-center">
                                            <button id="id_apply" type="button" class="btn btn-primary"
                                                    data-toggle="modal" data-target="#save_model">Apply
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    <label for="id_plan_name">plan name</label>
                                    <select id="id_plan_name" class="form-control" name="plan_name"
                                            value={{plan_name.planName}}
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="id_service_name">service name</label>
                                    <select id="id_service_name" class="form-control" name="service_name"
                                            value={{service_name.serviceName}}
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <table class="table">
                            <thead class="table">
                            <tr>
                                <th scope="col">No#</th>
                                <th scope="col">Service Price</th>
                                <th scope="col">Service Price(discount)</th>
                                <th scope="col">Provider</th>
                                <th scope="col">Provider(discount)</th>
                                <th scope="col">Total</th>
                                <th scope="col">Total(discount)</th>

                                <th scope="col">Invoice</th>
                            </tr>
                            </thead>

                            <tbody>
                            <tr>
                                <td><a id="id_invoice" href="{% url 'invoice-form'  pr=2 tpr=5%}">Subscribe</a>
                                </td>
                                <td><p id="price_id">0</p></td>
                                <td><p id="price_with_disc_id">0</p></td>
                                <td><p id="provider_price_id"></p></td>
                                <td><p id="provider_price_with_disc_id"></p></td>
                                <td><p id="total_price_id"></p></td>
                                <td><p id="total_price_with_disc_id"></td>
                                <td><p id="invoice_id"></td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

<button type="submit">Go</button>

<p>html(data.planPrice)
</p>

<script>

    $("#id_page").change(function(){
        var plan_duration = $("#id_plan_duration").val();
        var service_name = $("#id_service_name").val();
        var plan_name = $("#id_plan_name").val();
        var provider_name = $("#id_provider_name").val();
        var total_price = $("#id_total_price").val();
        var total_price_with_disc = $("#id_total_price_with_disc").val();
        $.ajax({
            url: '/ajax/extend-plan/',
            data: {
                'plan_duration': plan_duration,
                'plan_name':plan_name,
                'service_name':service_name,
                'total_price' :total_price,
                'provider_name':provider_name,
             },
            dataType: 'json',
            success: function (data) {

            var url = "{% url 'invoice-form' pr=-1 tpr=-2 %}".replace( '-1', tpr=data.planPrice_id).replace( '-2', tpr=data.total_price_with_disc);
               $("#id_invoice").attr("href", url );
               $("#price_id").html(data.planPrice);
               $("#price_with_disc_id").html(data.price_with_disc);
               $("#provider_price_id").html(data.provider_name); // this is price of provider cost
               $("#provider_price_with_disc_id").html(data.provider_name_disc); // this is price of provider cost with discount
               $("#total_price_id").html(data.total_price);
               $("#total_price_with_disc_id").html(data.total_price_with_disc);
               $("#invoice_id").html(data.service_name);
            }
        });
    });














</script>
{% endblock %}