portal/base/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("login/", views.loginPage, name="login"),
    path("logout/", views.logoutUser, name="logout"),
    path("register/", views.registerPage, name="register"),
    # path("", views.dashbord, name="home"),
    path("", views.home, name="home"),
    path("profile/<str:pk>", views.userProfile, name="user-profile"),
    path("vendors/", views.provider_activity.as_view(), name="list-vendors"),
    path(
        "edit-customer/<int:id>", views.EditCustomerView, name="edit-customer"
    ),
    path(
        "edit-customer-config/<int:id>",
        views.EditCustomerConfigView,
        name="edit-customer-config",
    ),
    path(
        "vendor-profile/<int:id>", views.vendorProfile, name="vendor-profile"
    ),
    path("plan/", views.planView, name="plan"),
    path("extend-plan/<int:id>", views.extendPlan_aj, name="extend-plan"),
    path(
        "ajax/extend-plan/",
        views.ValidateExtendPlan.as_view(),
        name="extend-plan-ajax",
    ),
    # path('invoice-form/<int:planPrice_id>/<int:total_price>', views.invoiceForm, name="invoice-form"),
    # path(r'^invoice-form/(?P<pr>\d+)(?:/(?P<tpr>\d+))?', views.invoiceDetailView, name="invoice-form"),
    # path(r'^invoice-form/(?P<pr>\d+)(?:/(?P<tpr>\d+))?', views.invoiceDetailView, name="invoice-form"),
    path(
        "invoice-form/<str:pr>/<str:tpr>",
        views.invoiceRegisterView,
        name="invoice-form",
    ),
    path(
        "<int:pk>/edit",
        views.invoiceDetailView.as_view(),
        name="invoice-edit",
    ),
    # (r'^question/(?P<pk>\d+)(?:/(?P<npk>\d+))?
    path("invoice-list/", views.invoiceList, name="invoice-list"),
    path("dashbord/", views.dashbord, name="dashbord"),
    path("index/", views.index, name="index"),
    # path('ticket/', views.createTicket, name="ticket"),
    # path('ticket/', views.ticketList, name="ticket"),
    path("about/", views.aboutUs, name="about"),
    path("test", views.test, name="test"),
    # path('edit-account/<int:id>', views.editAccountExchange, name='edit-account'),
    path(
        "account/<int:pk>/edit",
        views.EditAccountExchange.as_view(),
        name="edit-account",
    ),
    path(
        "account/<int:pk>/delete",
        views.DeleteAccountExchange.as_view(),
        name="delete-account",
    ),
    path(
        "create-account", views.createAccountExchange, name="create-account"
    ),
]

portal/portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("base.urls")),
    path("tickets/", include("tickets.urls")),
    path("signals/", include("signals.urls")),
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("img/favicon.ico")),
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portal/tickets/urls.py
from django.urls import path
from . import views

app_name = "tickets"
urlpatterns = [
    path("", views.TicketListView.as_view(), name="ticket-list"),
    path("create", views.TicketCreateView.as_view(), name="ticket-create"),
    path(
        "<int:pk>/add",
        views.TicketDetailExtendView.as_view(),
        name="ticket-add",
    ),
]

portal/tickets/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from base.models import Customer


class TicketSubject(models.Model):  # 1 to many
    name = models.CharField(max_length=50, null=False)
    status = models.IntegerField(default=1, null=False, blank=True)
    dsc = models.CharField(max_length=300, null=True, blank=True)
    updated = models.DateTimeField(null=True, blank=True)
    created = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = "ticket_subject"

    def __str__(self):
        return self.name


class Ticket(models.Model):
    PRIORITY_CHOICES = (
        ("Low", "Low"),
        ("Medium", "Medium"),
        ("High", "High"),
        ("Critical", "Critical"),
    )
    STATUS_CHOICES = (
        ("Open", "Open"),
        ("Waiting On Submitter", "Waiting On Submitter"),
        ("In Progress", "In Progress"),
        ("Waiting On Support", "Waiting On Support"),
        ("Resolved", "Resolved"),
    )
    ticketSubject = models.ForeignKey(TicketSubject, on_delete=models.CASCADE)
    priority = models.CharField(
        max_length=10, choices=PRIORITY_CHOICES, blank=True
    )
    status = models.CharField(
        max_length=40, choices=STATUS_CHOICES, blank=True
    )
    user = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True)
    updated = models.DateTimeField(null=True, blank=True)
    created = models.DateTimeField(null=True, blank=True)

    def how_many_days_old(self):
        delta = timezone.now() - self.created
        return delta.days

    # def shortened_subject_str(self):
    #     return self.subject[0:20]

    # def get_absolute_url(self):
    #     return reverse('tickets:ticket_detail', args=[str(self.id)])

    def __str__(self):
        return self.ticketSubject.name + "-" + str(self.id)

    class Meta:
        db_table = "ticket"


class TicketDetail(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.SET_NULL, null=True)
    status = models.IntegerField(default=1)
    req = models.CharField(max_length=500, null=True, blank=True)
    resp = models.CharField(max_length=1000, null=True, blank=True)
    updated = models.DateTimeField(null=True, blank=True)
    created = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = "ticket_dt"

portal/tickets/forms.py
from django import forms
from .models import Ticket, TicketDetail, TicketSubject
from django.forms import ModelForm
from django.forms import inlineformset_factory


class TicketForm(ModelForm):
    class Meta:
        model = Ticket
        fields = ["priority", "ticketSubject"]


class TicketSubjectForm(ModelForm):
    class Meta:
        model = TicketSubject
        fields = "__all__"


# class TicketForm(forms.ModelForm):
#     class Meta:
#         model = Ticket
#
#         widgets = {
#             'description': forms.Textarea(),
#             'creator': forms.HiddenInput(),
#         }
#
#         fields = [
#             'ticketType',
#             'subject',
#             'project',
#             'description',
#             'priority',
#             'status',
#             'creator',
#             'owner',
#         ]
#
#         # help_texts = {
#         #     'subject': 'Group to which this message belongs to',
#         # }
#
#         # error_messages={
#         #     'required': 'Please enter your name'
#         # }


class TicketDetailForm(ModelForm):
    class Meta:
        model = TicketDetail
        fields = ["req"]

portal/tickets/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from tickets.models import Ticket, TicketDetail, TicketSubject
from django.views.generic import ListView
from .forms import TicketForm, TicketSubjectForm, TicketDetailForm
from django.shortcuts import get_object_or_404, redirect
from django.db import connections
from datetime import datetime


class TicketUpdateView(UpdateView):
    model = TicketDetail
    form_class = TicketDetailForm
    template_name = "ticket_form.html"
    success_url = "/tickets/"

    def get_context_data(self, **kwargs):
        context = super(TicketUpdateView, self).get_context_data(**kwargs)
        t_detail = TicketDetail.objects.filter(
            id=self.kwargs.get("pk")
        ).last()
        t = Ticket.objects.get(id=t_detail.ticket_id)
        t_subjet = TicketSubject.objects.get(id=t.ticketSubject_id)
        context["ticket_title"] = t_subjet
        context["t_detail"] = t_detail

        return context


class TicketDetailExtendView(CreateView):
    model = TicketDetail
    # form_class = TicketDetailForm
    fields = ["req"]
    template_name = "ticket_form.html"
    success_url = "/tickets/"

    def get_context_data(self, **kwargs):
        context = super(TicketDetailExtendView, self).get_context_data(
            **kwargs
        )
        print(self.kwargs["pk"])
        # prev_ticket = TicketDetail.objects.filter(ticket=TicketDetail.objects.get(id=self.kwargs['pk']).ticket)
        prev_ticket = TicketDetail.objects.filter(
            ticket=self.kwargs["pk"]
        ).values()
        print(prev_ticket)
        context = {"prev_ticket": prev_ticket, "form": TicketDetailForm}
        return context

    def form_valid(self, form, **kwargs):
        # t = TicketDetail.objects.get(ticket=self.kwargs['pk'])
        form.instance.ticket_id = self.kwargs["pk"]
        form.instance.updated = datetime.now()
        return super().form_valid(form)


def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [dict(zip(columns, row)) for row in cursor.fetchall()]


class TicketListView(ListView):
    model = Ticket
    paginate_by = 4
    ordering = "-updated"
    context_object_name = "t_detail"
    template_name = "ticket_list.html"

    def get_queryset(self):
        try:
            with connections["default"].cursor() as cursor:
                cursor.execute(
                    f"select  t_id, dt_id, req , resp ,status, priority, created,updated  from v_ticket where user_id={self.request.user.id}"
                )
                return dictfetchall(cursor)
        except:
            print("Except None")
            context = {"t_detail": "None"}
            return context


class TicketCreateView(CreateView):
    form_class = TicketForm
    template_name = "ticket_create.html"
    success_url = "/tickets/"

    def get_context_data(self, **kwargs):
        context = super(TicketCreateView, self).get_context_data(**kwargs)
        context = {"form": TicketForm, "form_detail": TicketDetailForm}
        return context

    def post(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        ticket_detail = TicketDetailForm(self.request.POST)

        if form.is_valid() and ticket_detail.is_valid():
            return self.form_valid(form, ticket_detail)
        else:
            print("form.errors")
            return self.form_invalid(form, ticket_detail)

    def form_valid(self, form, ticket_detail):
        self.object = form.save(commit=False)
        form.instance.user = self.request.user.customer
        form.instance.status = "Open"
        form.instance.updated = datetime.now()
        form.instance.created = datetime.now()
        self.object.save()
        t_dt = ticket_detail.save(commit=False)
        t_dt.ticket = self.object
        t_dt.updated = datetime.now()
        t_dt.created = datetime.now()
        t_dt.save()
        return redirect("/tickets/")

    def form_invalid(self, form, ticket_detail_formset):
        return self.render_to_response(
            self.get_context_data(form=form, ticket_detail=ticket_detail)
        )

portal/tickets/templates/ticket_create.html
{% extends "main.html" %}
{% block content %}

<div class="card card-default mb-0">
    <div class="row bg-white no-gutters chat">
    </div>
    <div class="col-lg-11 col-xl-12">
        <!-- Chats -->
        <div class="chat-right-side">
            <div class="media media-chat align-items-center mb-0 media-chat-header" href="#">
                <img class="rounded-circle mr-3" src="{{request.user.customer.avatar.url}}" alt="Image">
                <div class="media-body w-100">
                    <div class="d-flex justify-content-between align-items-center">
                        <h3 class="heading-title mb-0"><a href="{% url  'edit-customer' request.user.id %}">{{request.user}}</a>
                        </h3>
                        <div class="dropdown">
                            <a class="dropdown-toggle icon-burger-mini" href="#" role="button" id="dropdownMenuLink"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-display="static">
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
                                <a class="dropdown-item" href="{% url  'edit-customer' request.user.id %}">Profile</a>
                                <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% for prev in prev_ticket %}
            <br/>
            <div class="chat-right-content" id="chat-right-content" data-simplebar>
                <div class="media media-chat media-left">
                    <img class="rounded-circle mr-3" src="{{request.user.customer.avatar.url}}" alt="Image">

                    <div class="media-body">
                        <p class="message"> {{ prev.req }}</p>
                        <div class="date-time">{{prev.updated}}</div>
                    </div>
                </div>

                <div class="media media-chat media-right">
                    <div class="media-body">
                        <p class="message"> {{ prev.resp }}</p>
                        <div class="date-time">{{prev.updated }}</div>
                    </div>
                    <img class="rounded-circle ml-3" src="/media/profile_image/pic_resp.jpg" alt="Image">
                </div>
                {%endfor%}

            </div>

            <form class="px-5 pb-3" method="post">
                {% csrf_token %}
                <div class="row mt-5">

                    <label for="id_priority">Priority</label>
                    <select id="id_priority" class="form-control" name="priority"  value="{{form.priority}}
                    </select>
                    <label for="id_ticketSubject">Subject</label>
                    <select id="id_ticketSubject" class="form-control" name="ticketSubject" value="{{form.ticketSubject}}
                    </select>
                    <hr/>
                    <label for="id_req">Message</label>
                    <input type="text" name="req"   id="id_req" class="form-control mb-3" placeholder="Type your message here">
                </div>

                <button id="id_submit" type="submit" class="btn btn-primary">
                    Send Message
                </button>
            </form>
        </div>

    </div>
</div>

{% endblock %}

portal/tickets/templates/ticket_form.html
{% extends "main.html" %}
{% block content %}


<div class="card card-default mb-0">
    <div class="row bg-white no-gutters chat">
    </div>
    <div class="col-lg-11 col-xl-12">
        <!-- Chats -->
        <div class="chat-right-side">
            <div class="media media-chat align-items-center mb-0 media-chat-header" href="#">
                <img class="rounded-circle mr-3" src="{{request.user.customer.avatar.url}}" alt="Image">
                <div class="media-body w-100">
                    <div class="d-flex justify-content-between align-items-center">
                        <h3 class="heading-title mb-0"><a href="{% url  'edit-customer' request.user.id %}">{{request.user}}</a>
                        </h3>
                        <div class="dropdown">
                            <a class="dropdown-toggle icon-burger-mini" href="#" role="button" id="dropdownMenuLink"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-display="static">
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
                                <a class="dropdown-item" href="{% url  'edit-customer' request.user.id %}">Profile</a>
                                <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% for prev in prev_ticket %}
            <br/>
            <div class="chat-right-content" id="chat-right-content" data-simplebar>
                <div class="media media-chat media-left">
                    <img class="rounded-circle mr-3" src="{{request.user.customer.avatar.url}}" alt="Image">

                    <div class="media-body">
                        <p class="message"> {{ prev.req }}</p>
                        <div class="date-time">{{prev.updated}}</div>
                    </div>
                </div>

                <div class="media media-chat media-right">
                    <div class="media-body">
                        <p class="message"> {{ prev.resp }}</p>
                        <div class="date-time">{{prev.updated }}</div>
                    </div>
                    <img class="rounded-circle ml-3" src="/media/profile_image/pic_resp.jpg" alt="Image">
                </div>
                {%endfor%}

            </div>

            <form class="px-5 pb-3" method="post">
                {% csrf_token %}
                <div class="row mt-5">
                <hr/>
                    <input type="text" name="req" id="id_req" class="form-control mb-3"
                           placeholder="Type your message here">
                </div>
                <button id="id_submit" type="submit" class="btn btn-primary">
                    Send Message
                </button>
            </form>
        </div>

    </div>
</div>


{% endblock %}

portal/tickets/templates/ticket_list.html
{% extends "main.html" %}
{% block content %}

<div class="card card-default mb-0">
    <div class="row bg-white no-gutters chat">
        <div class="col-lg-11 col-xl-12">
            <div class="chat-right-side">
                <div class="media media-chat align-items-center mb-0 media-chat-header" href="#">
                    <img class="rounded-circle mr-3" src="/media/echnical-support.png" alt="Image">
                    <div class="media-body w-100">
                        <div class="d-flex justify-content-between align-items-center">
                            <h3 class="heading-title mb-0"><a href="{% url  'edit-customer' request.user.id %}">{{request.user}}</a>
                            </h3>
                            <div class="dropdown">
                                <a href="{% url 'tickets:ticket-create'  %}" role="button" id="dropdownMenuLink"
                                   aria-haspopup="true" aria-expanded="false" data-display="static">
                                    <button id="id_submit" type="button" class="btn btn-primary" data-toggle="modal"
                                            data-target="#save_model">ADD Ticket
                                    </button>

                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <ul class="list-unstyled border-top mx-5" id="chat-left-content" data-simplebar>
                    {% for tr in t_detail %}
                    <li><a href="{% url 'tickets:ticket-add' tr.T_ID %}">

                        <div class="media media-chat media-left">
                            <div class="media-body">
                                <p class="message"> Ticket No. {{ tr.T_ID }}#</p>
                                <p class="message"> {{ tr.REQ|slice:":100" }}...
                                    <span class="badge badge-danger">{{ tr.PRIORITY }}</span></p>
                                <p class="message"> {{ tr.RESP|slice:":100" }}... </p>
                                <div class="date-time"> {{ tr.STATUS }} {{ tr.CREATED|timesince }} ago</div>
                            </div>

                        </div>
                    </a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    <div>


        <!--     -->


        <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
        </div>

    </div>
</div>
{% endblock content %}

portal/tickets/templates/ticket_update.html
{% extends "header.html" %}
{% load static %}
{% block page_content %}

<div class="container">
    <form method='POST'> {% csrf_token %}
        {% include 'ticket_form.html' %}
        <input type='submit' value='Save' />
    </form>
</div>
{% endblock %}